services:
  admin_database:
    image: postgres:16-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./scripts/database.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: admin
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"

  admin_app:
    image: adm_simcc  
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - admin_database
    env_file:
      - .env

volumes:
  pgdata: